version: "3.9"

volumes:
  frontend_node_modules:

services:
  frontend:
    build:
      context: ./frontend/
      target: dev
    tty: true
    restart: always
    ports:
      - "3030:3000"
    volumes:
      - ./frontend:/frontend-app
      - frontend_node_modules:/frontend-app/node_modules
