version: "3.9"

volumes:
  frontend_node_modules:

services:
  frontend:
    build:
      context: ./frontend/
      target: dev
    tty: true
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - frontend_node_modules:/app/frontend/node_modules
  backend:
    build:
      context: ./backend/
      target: dev
    tty: true
    restart: always
    ports:
      - 127.0.0.1:5000:5000
    volumes:
      - .:/app