version: "3.9"

volumes:
  frontend_node_modules:

services:
  frontend:
    build:
      context: ./frontend/
      target: main
    tty: true
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app/frontend
      - frontend_node_modules:/app/frontend/node_modules
  backend:
    build:
      context: ./backend/
      target: dev
    tty: true
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app/backend